statsApp/urls.py
from django.urls import path, include
from statsApp import views
from statsApp.views import PlayerListView

urlpatterns = [
    
]

website/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from statsApp import views
from statsApp.models import Player, Team
from statsApp.views import PlayerListView, PlayerDetailView, TeamsListView, TeamDetailView, GameLogDetailView



urlpatterns = [
    path('', views.landing, name = 'landing'),
    path('players/', PlayerListView.as_view(extra_context={'players_page': 'active'})),
    path('teams/', TeamsListView.as_view(extra_context={'teams_page': 'active'})),
    path('series/<int:pk>/', GameLogDetailView.as_view(extra_context={})),
    path('stats/', views.stats, name = 'stats'),
    path('matchup_prediction/', views.matchup_prediction, name = 'matchup_prediction'),
    path('FAQ/', views.FAQ, name = 'FAQ'),
    path('admin/', admin.site.urls),
    path('standings/', views.standings, name = 'standings'),
    path('mock_draft/', views.mock_draft, name = 'mock_draft'),
    path('players/<int:pk>/', PlayerDetailView.as_view(extra_context={'players_page': 'active'}), name='player-detail'),
    path('teams/<int:pk>/', TeamDetailView.as_view(extra_context={'teams_page': 'active'}), name='team-detail'),
]

statsApp/models.py
from django.db import models

# Create your models here.
class Team(models.Model):
    name = models.CharField(max_length=100, default = '')
    wins = models.IntegerField(default = 0)
    losses = models.IntegerField(default = 0)
    gp = models.IntegerField(default = 0)
    division = models.CharField(max_length = 2)
    abv = models.CharField(max_length = 3)
    average_runs_scored = models.DecimalField(default = 0.0, decimal_places = 3, max_digits = 4)
    average_runs_allowed = models.DecimalField(default = 0.0, decimal_places = 3, max_digits = 4)
    D_value = models.DecimalField(default = 1.0, decimal_places = 3, max_digits = 4)

    def __str__(self):
        return self.name

class Player(models.Model):
    name = models.CharField(max_length=100, default = '')
    team = models.ForeignKey(Team, on_delete = models.CASCADE, null=True)
    gp = models.IntegerField(default = 0)
    ab = models.IntegerField(default = 0)
    h = models.IntegerField(default = 0)
    db = models.IntegerField(default = 0)
    tr = models.IntegerField(default = 0)
    hr = models.IntegerField(default = 0)
    rbi = models.IntegerField(default = 0)
    k = models.IntegerField(default = 0)
    bb = models.IntegerField(default = 0)
    ba = models.DecimalField(default = 0.0, decimal_places = 3, max_digits = 4)
    sp = models.DecimalField(default = 0.0, decimal_places = 3, max_digits = 4)
    obp = models.DecimalField(default = 0.0, decimal_places = 3, max_digits = 4)
    ops = models.DecimalField(default = 0.0, decimal_places = 3, max_digits = 4)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

class GameLog(models.Model):
    date = models.DateField()
    team1 = models.ForeignKey(Team, on_delete = models.DO_NOTHING, null=True, related_name = 'team1')
    team2 = models.ForeignKey(Team, on_delete = models.DO_NOTHING, null=True, related_name = 'team2')
    team_1_victories = models.IntegerField(default = 0)
    team_2_victories = models.IntegerField(default = 0)
    game_1_team1_score = models.IntegerField(default = 0)
    game_1_team2_score = models.IntegerField(default = 0)
    game_2_team1_score = models.IntegerField(default = 0)
    game_2_team2_score = models.IntegerField(default = 0)
    game_3_team1_score = models.IntegerField(default = 0, blank = True)
    game_3_team2_score = models.IntegerField(default = 0, blank = True)

    class Meta:
        ordering = ["-date"]

    def save(self, *args, **kwargs):
        team1 = self.team1
        team2 = self.team2
        team1.wins += self.team_1_victories
        team1.losses += self.team_2_victories
        team2.wins += self.team_2_victories
        team2.losses += self.team_1_victories

        # team 1
        t1_total_runs_scored = team1.gp*team1.average_runs_scored + self.game_1_team1_score + self.game_2_team1_score + self.game_3_team1_score
        t1_total_runs_allowed = team1.gp*team1.average_runs_allowed + self.game_1_team2_score + self.game_2_team2_score + self.game_3_team2_score

        i = 0
        t1_d_total = team1.D_value * team1.gp
        for score in [self.game_1_team1_score, self.game_2_team1_score, self.game_3_team1_score]:
            if (i == self.team_1_victories + self.team_2_victories):
                break
            else:
                if team2.average_runs_allowed == 0:
                    t1_d_total += 1
                else:
                    t1_d_total += score/team2.average_runs_allowed
            i += 1

        team1.gp += self.team_1_victories + self.team_2_victories
        team1.average_runs_scored = t1_total_runs_scored / team1.gp
        team1.D_value = t1_d_total / team1.gp


        # team 2
        t2_total_runs_scored = team2.gp*team2.average_runs_scored + self.game_1_team2_score + self.game_2_team2_score + self.game_3_team2_score
        t2_total_runs_allowed = team2.gp*team2.average_runs_allowed + self.game_1_team1_score + self.game_2_team1_score + self.game_3_team1_score

        i = 0
        t2_d_total = team2.D_value * team2.gp
        for score in [self.game_1_team2_score, self.game_2_team2_score, self.game_3_team2_score]:
            if (i == self.team_1_victories + self.team_2_victories):
                break
            else:
                if team1.average_runs_allowed == 0:
                    t2_d_total += 1
                else:
                    t2_d_total += score/team1.average_runs_allowed
            i += 1

        team2.gp += self.team_1_victories + self.team_2_victories
        team2.average_runs_scored = t2_total_runs_scored / team2.gp
        team2.average_runs_allowed = t2_total_runs_allowed / team2.gp
        team2.D_value = t2_d_total / team2.gp

        team1.average_runs_allowed = t1_total_runs_allowed / team1.gp

        team1.save()
        team2.save()
        super(GameLog, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.team1} ({self.team_1_victories}) vs {self.team2} ({self.team_2_victories}) {self.date}'

class PlayerPerformance(models.Model):
    player = models.ForeignKey(Player, models.DO_NOTHING, null = True)
    game_log = models.ForeignKey(GameLog, on_delete = models.DO_NOTHING, null = True)
    hits = models.IntegerField(default = 0)
    at_bats = models.IntegerField(default = 0)
    doubles = models.IntegerField(default = 0)
    triples = models.IntegerField(default = 0)
    hrs = models.IntegerField(default = 0)
    rbis = models.IntegerField(default = 0)
    k = models.IntegerField(default = 0)
    bb = models.IntegerField(default = 0)

    def calculateOBP(self, hits, walks, ab):
        if ab == 0:
            return 0
        return round((hits + walks) / (ab + walks), 3)

    def calculateSlug(self, single, double, triple, hr, ab):
        if (ab == 0):
            return 0
        return round ((single + 2*double + 3*triple + 4*hr) / ab, 3)

    def save(self, *args, **kwargs):
        p = self.player
        p.ab += self.at_bats
        p.h += self.hits
        p.db += self.doubles
        p.tr += self.triples
        p.hr += self.hrs
        p.rbi += self.rbis
        p.k += self.k
        p.bb += self.bb
        p.ba = round(float(p.h)/p.ab, 3)
        p.obp = self.calculateOBP(p.h, p.bb, p.ab)
        p.sp = self.calculateSlug(p.h - p.db - p.tr - p.hr, p.db, p.tr, p.hr, p.ab)
        p.ops = p.obp + p.sp
        p.gp += self.game_log.team_1_victories + self.game_log.team_2_victories
        p.save()
        super(PlayerPerformance, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.player.name} - {self.game_log}'

statsApp/views.py
from django.shortcuts import render
from .models import Player, Team, PlayerPerformance, GameLog
import statsApp.df_manipulation as dfm
from django.views.generic import ListView
from django.views.generic import DetailView
from .forms import MatchupPredictor
from django.http import HttpResponse, HttpResponseRedirect
import numpy as np
import pandas as pd
import plotly.express as px


# Create your views here.
def landing(request):
    my_dict = {"home_page": 'active'}

    return render(request,'landing.html', context=my_dict)

def stats(request):
    # setup dataframe
    df = dfm.get_df(Player.objects.all())

    byHR = df[df['ab'] > 5].sort_values('hr', ascending = False).iloc[0:10][['name', 'hr']]
    byBA = df[df['ab'] > 5].sort_values('ba', ascending = False).iloc[0:10][['name', 'ba']]
    byOPS = df[df['ab'] > 5].sort_values('ops', ascending = False).iloc[0:10][['name', 'ops']]
    byH = df[df['ab'] > 5].sort_values('h', ascending = False).iloc[0:10][['name', 'h']]
    byRBI = df[df['ab'] > 5].sort_values('rbi', ascending = False).iloc[0:10][['name', 'rbi']]

    byHRlist = list(byHR.to_dict('records'))
    byBAlist = list(byBA.to_dict('records'))
    byOPSlist = list(byOPS.to_dict('records'))
    byHlist = list(byH.to_dict('records'))
    byRBIlist = list(byRBI.to_dict('records'))

    hrRankList = sorted(list(dict(byHR['hr']).values()))[::-1]
    baRankList = sorted(list(dict(byBA['ba']).values()))[::-1]
    OPSRankList = sorted(list(dict(byOPS['ops']).values()))[::-1]
    hRankList = sorted(list(dict(byH['h']).values()))[::-1]
    rbiRankList = sorted(list(dict(byRBI['rbi']).values()))[::-1]

    for p in byHRlist:
        for i in range(len(hrRankList)):
            if p['hr'] == hrRankList[i]:
                p['rank'] = i+1
                break
        p['pk'] = Player.objects.get(name = p['name']).pk

    for p in byBAlist:
        for i in range(len(baRankList)):
            if p['ba'] == baRankList[i]:
                p['rank'] = i+1
                break
        p['pk'] = Player.objects.get(name = p['name']).pk

    for p in byOPSlist:
        for i in range(len(OPSRankList)):
            if p['ops'] == OPSRankList[i]:
                p['rank'] = i+1
                break
        p['pk'] = Player.objects.get(name = p['name']).pk

    for p in byHlist:
        for i in range(len(hRankList)):
            if p['h'] == hRankList[i]:
                p['rank'] = i+1
                break
        p['pk'] = Player.objects.get(name = p['name']).pk

    for p in byRBIlist:
        for i in range(len(rbiRankList)):
            if p['rbi'] == rbiRankList[i]:
                p['rank'] = i+1
                break
        p['pk'] = Player.objects.get(name = p['name']).pk


    my_dict = {'byHR': byHRlist, 'byBA': byBAlist, 'byOPS': byOPSlist, 'byH': byHlist, 'byRBI': byRBIlist, "stats_page": 'active'}

    return render(request,'stats.html', context=my_dict)

def standings(request):

    nl_teams = list(Team.objects.filter(division = 'NL'))
    al_teams = list(Team.objects.filter(division = 'AL'))

    nl_teams = sorted(nl_teams, key = lambda x : (x.wins - x.losses)/2, reverse = True)
    al_teams = sorted(al_teams, key = lambda x : (x.wins - x.losses)/2, reverse = True)

    nl_teams = [[n, 0] for n in nl_teams]
    al_teams = [[a, 0] for a in al_teams]


    ind = 0
    for t in nl_teams:
        pos_val = t[0].wins - .001 * t[0].losses
        c = 0
        for p in nl_teams:
            c += 1
            if pos_val == p[0].wins - .001 * p[0].losses:
                nl_teams[ind][1] = c
                ind += 1
                break

    ind = 0
    for t in al_teams:
        pos_val = t[0].wins - .001 * t[0].losses
        c = 0
        for p in al_teams:
            c += 1
            if pos_val == p[0].wins - .001 * p[0].losses:
                al_teams[ind][1] = c
                ind += 1
                break

    nl_teams.insert(3, {'warning': 'table-warning'})
    al_teams.insert(3, {'warning': 'table-warning'})

    nl_top = (nl_teams[0][0].wins - nl_teams[0][0].losses)/2
    al_top = (al_teams[0][0].wins - al_teams[0][0].losses)/2

    my_dict = {'al_teams' : al_teams, 'nl_teams' : nl_teams, 'standings_page' : 'active', 'al_top' : al_top, 'nl_top' : nl_top}
    return render(request,'standings.html', context=my_dict)



def mock_draft(request):
    df = dfm.get_erg(list(Player.objects.all()), list(Team.objects.all()))
    players_list = []
    for index, row in df.iterrows():
        players_list.append(Player.objects.get(name = row['name']))
    rounds = []
    players_list = players_list[0:56]
    for i in range(0, len(players_list), 14):
        rounds.append(players_list[i: i+14])

    for r in range(len(rounds)):
        for p in range(len(rounds[r])):
            rounds[r][p] = [p+1, rounds[r][p]]
        rounds[r] = [r+1, rounds[r]]

    my_dict = {'rounds': rounds}
    return render(request,'mock_draft.html', context=my_dict)

def FAQ(request):
    my_dict = {}
    return render(request,'FAQ.html', context=my_dict)

class PlayerListView(ListView):
    model = Player
    ordering = ['name']

class TeamsListView(ListView):
    model = Team
    ordering = ['name']

    team_players_dict = {str(t.pk): [] for t in Team.objects.all()}

    def get_context_data(self, **kwargs):
        context = super(TeamsListView,self).get_context_data(**kwargs)
        team_players_dict = {}
        for t in Team.objects.all():
            team_players_dict[str(t.pk)] = []
            for p in Player.objects.filter(team=t.pk):
                team_players_dict[str(t.pk)].append(p)

        context['players'] = team_players_dict
        return context

class PlayerDetailView(DetailView):
    queryset = Player.objects.all()

class GameLogDetailView(DetailView):
    queryset = GameLog.objects.all()
    def get_context_data(self, **kwargs):
        team1 = Team.objects.get(name = self.object.team1)
        team2 = Team.objects.get(name = self.object.team2)
        performances = list(self.object.playerperformance_set.all())
        team1_performances = []
        team2_performances = []
        for p in performances:
            if p.player.team == team1:
                team1_performances.append(p)
            elif p.player.team == team2:
                team2_performances.append(p)

        games = [] # will store games in (w/l, team1, team2, score) format

        i = 0
        for scores in [[self.object.game_1_team1_score, self.object.game_1_team2_score], [self.object.game_2_team1_score, self.object.game_2_team2_score],
                [self.object.game_3_team1_score, self.object.game_3_team2_score]]:
            if i == self.object.team_1_victories + self.object.team_2_victories:
                break
            if scores[0] > scores[1]:
                # home win
                games.append(['W', team1.abv, team2.abv, f'{scores[0]} - {scores[1]}'])
            else:
                games.append(['L', team1.abv, team2.abv, f'{scores[0]} - {scores[1]}'])
            i += 1

        context = {'team1_performances': team1_performances, 'team2_performances': team2_performances, 'games': games, 'team1pk': team1.pk, 'team2pk': team2.pk,
                    'team_1_victories': self.object.team_1_victories, 'team_2_victories': self.object.team_2_victories}
        return context


class TeamDetailView(DetailView):
    queryset = Team.objects.all()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        team_pk = Team.objects.get(name = self.object)
        context['players'] = list(Player.objects.filter(team=team_pk))
        recent_series = list(self.object.team1.all()) + list(self.object.team2.all())
        recent_series.sort(key = lambda x : x.date, reverse = True)

        series_summaries = []
        for s in recent_series:
            if s.team1 == self.object:
                curr_team_wins = s.team_1_victories
                opps_team_wins = s.team_2_victories
                opp_team = s.team2.abv
                opp_teampk = s.team2.pk
            elif s.team2 == self.object:
                curr_team_wins = s.team_2_victories
                opps_team_wins = s.team_1_victories
                opp_team = s.team1.abv
                opp_teampk = s.team1.pk
            result = 'L'
            if curr_team_wins > opps_team_wins:
                result = 'W'
            series_summaries.append([result, opp_team, f'{curr_team_wins} - {opps_team_wins}', opp_teampk, s.pk])

        context['recent_series'] = series_summaries

        return context

def matchup_prediction(request):
    form = MatchupPredictor
    my_dict = {'form': form}
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = MatchupPredictor(request.POST)
        # check whether it's valid:
        if form.is_valid():
            team1_obj = Team.objects.get(name = form.cleaned_data['team1'])
            team2_obj = Team.objects.get(name = form.cleaned_data['team2'])

            team_1_estimate = team1_obj.D_value * np.sqrt(team1_obj.average_runs_scored) * np.sqrt(team2_obj.average_runs_allowed)
            team_2_estimate = team2_obj.D_value * np.sqrt(team2_obj.average_runs_scored) * np.sqrt(team1_obj.average_runs_allowed)

            if form.cleaned_data['team1'] == form.cleaned_data['team2']:
                pass
            elif team_1_estimate == 0 or team_2_estimate == 0:
                pass
            else:
                sd = 2.8
                team_1_wins = 0
                num_iters = 1000
                team_1_estimate = np.sqrt(team_1_estimate)
                team_2_estimate = np.sqrt(team_2_estimate)
                for i in range(num_iters):
                    team_1_random = np.random.normal(team_1_estimate, sd)
                    team_2_random = np.random.normal(team_2_estimate, sd)
                    if team_1_random > team_2_random:
                        team_1_wins += 1

templates/statsApp/gamelog_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load extras %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'series_detail.css' %}">
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
  <div class="tables">
    <div class="player-table">
      <br>
      <h2>{{ games.0.1 }}({{ team_1_victories }}) @ {{ games.0.2 }}({{ team_2_victories }}) </h2>
      <table class="table table-dark table-hover">
        <thead>
          <tr>
            <th scope="col">Result</th>
            <th scope="col">Home Team</th>
            <th scope="col">Away Team</th>
            <th scope="col">Score</th>
          </tr>
        </thead>
        <tbody>
          {% for g in games %}
          <tr>
            <td class = '{{ g.0 }}'>{{ g.0 }}</td>
            <td><a href='/teams/{{ team1pk }}'>{{ g.1 }}</a></td>
            <td><a href='/teams/{{ team2pk }}'>{{ g.2 }}</td>
            <td>{{ g.3 }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="team1-table">
      <br>
      <h2>{{ games.0.1 }} Performances</h2>
      <table class="table table-striped table-dark table-hover">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">AB</th>
            <th scope="col">H</th>
            <th scope="col">HR</th>
            <th scope="col">RBI</th>
            <th scope="col">K</th>
            <th scope="col">BB</th>

          </tr>
        </thead>
        <tbody>
          {% for p in team1_performances %}
          <tr>
            <td><a href='/players/{{ p.player.pk }}'>{{ p.player.name }}</td>
            <td>{{ p.at_bats }}</a></td>
            <td>{{ p.hits }}</td>
            <td>{{ p.hrs }}</td>
            <td>{{ p.rbis }}</td>
            <td>{{ p.k }}</td>
            <td>{{ p.bb }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="team2-table">
      <br>
      <h2>{{ games.0.2 }} Performances</h2>
      <table class="table table-striped table-dark table-hover">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">AB</th>
            <th scope="col">H</th>
            <th scope="col">HR</th>
            <th scope="col">RBI</th>
            <th scope="col">K</th>
            <th scope="col">BB</th>
          </tr>
        </thead>
        <tbody>
          {% for p in team2_performances %}
          <tr>
            <td>{{ p.player.name }}</td>
            <td>{{ p.at_bats }}</a></td>
            <td>{{ p.hits }}</td>
            <td>{{ p.hrs }}</td>
            <td>{{ p.rbis }}</td>
            <td>{{ p.k }}</td>
            <td>{{ p.bb }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</body>
</html>
{% endblock %}

templates/statsApp/player_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'player_detail.css' %}">
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="main-content">
    <div class="stats-table">
    <table class="table table-striped table-dark table-hover">
      <thead>
        <tr>
        <th scope="col"></th>
        <th scope="col">Name</th>
        <th scope="col">GP</th>
        <th scope="col">AB</th>
        <th scope="col">H</th>
        <th scope="col">2B</th>
        <th scope="col">3B</th>
        <th scope="col">HR</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row"></th>
        <td>{{ object.name }}</td>
        <td>{{ object.gp }}</td>
        <td>{{ object.ab }}</td>
        <td>{{ object.h }}</td>
        <td>{{ object.db }}</td>
        <td>{{ object.tr }}</td>
        <td>{{ object.hr }}</td>
      </tr>
    </tbody>
  </table>
</div>
  <div class="stats-table">
  <table class="table table-striped table-dark table-hover">
    <thead>
      <tr>
  <th scope="col">RBI</th>
  <th scope="col">K</th>
  <th scope="col">BB</th>
  <th scope="col">BA</th>
  <th scope="col">OBP</th>
  <th scope="col">SP</th>
  <th scope="col">OPS</th>
</tr>
</thead>
<tbody>
  <tr>
  <td>{{ object.rbi }}</td>
  <td>{{ object.k }}</td>
  <td>{{ object.bb }}</td>
  <td>{{ object.ba }}</td>
  <td>{{ object.obp }}</td>
  <td>{{ object.sp }}</td>
  <td>{{ object.ops }}</td>
</tr>
</tbody>
</table>
  </div>
</div>
<br>
<br>
<br>
  </body>
  {% endblock %}
</html>

templates/statsApp/player_list.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'team_list.css' %}">

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <ul class="list-group">
    {% for p in object_list %}
        <li class="list-group-item list-group-item-dark"><a style = color:black href="/players/{{ p.pk }}">{{ p.name }}</a></li>
    {% endfor %}
</ul>
  </body>
  {% endblock %}
</html>